# NAV History Cleaning

In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/02_nav_history.csv")

In [2]:
print(df.dtypes)

amfi_code      int64
date             str
nav          float64
dtype: object

In [3]:
print(df.shape)

(46000, 3)

In [4]:
print(df.head())

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [5]:
df['date'] = pd.to_datetime(df['date'])

In [6]:
df['date'].info

<bound method Series.info of 0       2022-01-03
1       2022-01-04
2       2022-01-05
3       2022-01-06
4       2022-01-07
           ...
45995   2026-05-25
45996   2026-05-26
45997   2026-05-27
45998   2026-05-28
45999   2026-05-29
Name: date, Length: 46000, dtype: datetime64[us]>

In [7]:
df.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [8]:
df.head()

   amfi_code       date      nav
0     119551 2022-01-03  54.3856
1     119551 2022-01-04  54.3474
2     119551 2022-01-05  54.6869
3     119551 2022-01-06  55.4550
4     119551 2022-01-07  55.3692

In [9]:
df = df.sort_values(by=['amfi_code','date'])

In [10]:
print(df.duplicated().sum())

0

In [11]:
print(df.isnull().sum())

amfi_code    0
date         0
nav          0
dtype: int64

In [12]:
print(df.isna().sum())

amfi_code    0
date         0
nav          0
dtype: int64

In [13]:
print((df['nav'] <= 0).sum())

0

In [14]:
df.to_csv('../data/processed/nav_history_cleaned.csv', index=False)

# Investor Transaction Cleaning

In [27]:
df = pd.read_csv("../data/raw/08_investor_transactions.csv")

In [28]:
df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [29]:
df['transaction_type'].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [30]:
df.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [31]:
print((df['amount_inr'] <= 0).sum())

0

In [32]:
df['kyc_status'].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [33]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

In [34]:
df['transaction_date'].info()

<class 'pandas.Series'>
RangeIndex: 32778 entries, 0 to 32777
Series name: transaction_date
Non-Null Count  Dtype
--------------  -----
32778 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 256.2 KB

In [35]:
print(df.isnull().sum())

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [36]:
print(df.duplicated().sum())

0

In [37]:
df.to_csv('../data/processed/investor_transaction.csv',index=False)

# Scheme Performace Cleaning

In [41]:
df7 = pd.read_csv("../data/raw/07_scheme_performance.csv")

In [42]:
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [44]:
df7['return_1yr_pct'] = pd.to_numeric(df7['return_1yr_pct'])

In [45]:
df7['return_3yr_pct'] = pd.to_numeric(df7['return_3yr_pct'])

In [46]:
df7['return_5yr_pct'] = pd.to_numeric(df7['return_5yr_pct'])

In [47]:
df7.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [48]:
df7[['return_1yr_pct',
     'return_3yr_pct',
     'return_5yr_pct',
     'benchmark_3yr_pct']].describe()

       return_1yr_pct  return_3yr_pct  return_5yr_pct  benchmark_3yr_pct
count       40.000000       40.000000       40.000000          40.000000
mean        14.376000       14.089000       14.516750          12.835500
std          4.883023        4.617253        4.454021           4.740972
min          4.260000        5.140000        5.430000           3.960000
25%         11.735000       12.035000       12.340000          10.690000
50%         14.620000       14.205000       14.185000          13.090000
75%         16.392500       15.882500       17.585000          14.775000
max         24.930000       23.390000       23.800000          22.160000

# Observation:
### No anomalous values were found in the return columns.
### All return percentages fall within a reasonable range (approximately 4% to 25%)...

In [53]:
invalid_expense = df7[
    (df7['expense_ratio_pct'] < 0.1) |
    (df7['expense_ratio_pct'] > 2.5)
]

print(invalid_expense)

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

# Observation:
#### All expense ratio values lie within the expected range of 0.1% to 2.5%.
#### No invalid or suspicious expense ratio values were found.

In [54]:
df7.to_csv('../data/processed/scheme_performance.csv',index=False)